import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [webextensions-declarations website](https://github.com/cypressious/kotlin-webextensions-declarations) */
    const val webextensions_declarations: String =
            "com.github.cypressious.kotlin-webextensions-declarations:webextensions-declarations:" + Versions.webextensions_declarations

    const val build_scan_plugin: String =
            "com.gradle:build-scan-plugin:" + Versions.build_scan_plugin

    const val gradle_kotlin_dsl_libs: String =
            "jmfayard.github.io:gradle-kotlin-dsl-libs:" + Versions.gradle_kotlin_dsl_libs

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-js website](https://kotlinlang.org/) */
    const val kotlin_stdlib_js: String =
            "org.jetbrains.kotlin:kotlin-stdlib-js:" + Versions.org_jetbrains_kotlin
}
